package models

import (
	"time"
)

// KYCRecord represents a Know Your Customer record
type KYCRecord struct {
	ID        int       `json:"id"`
	UserID    int       `json:"user_id"`
	Status    string    `json:"status"` // e.g., "pending", "approved", "rejected"
	DocumentType string `json:"document_type"`
	DocumentID string   `json:"document_id"`
	IssueDate time.Time `json:"issue_date"`
	ExpiryDate time.Time `json:"expiry_date"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// TransactionMonitoringAlert represents an alert generated by transaction monitoring
type TransactionMonitoringAlert struct {
	ID            int       `json:"id"`
	TransactionID int       `json:"transaction_id"`
	UserID        int       `json:"user_id"`
	RuleTriggered string    `json:"rule_triggered"`
	Severity      string    `json:"severity"` // e.g., "low", "medium", "high"
	Status        string    `json:"status"`   // e.g., "open", "closed", "escalated"
	Description   string    `json:"description"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}
